DMQUYETTIEN/DMQUYETTIEN/Models/BangSanPham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMQUYETTIEN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangSanPham
    {
        public int id { get; set; }
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public int Loai_id { get; set; }
        public int GiaBan { get; set; }
        public int GiaGoc { get; set; }
        public int GiaGop { get; set; }
        public int SoLuongTon { get; set; }
    
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}

DMQUYETTIEN/DMQUYETTIEN/Controllers/BangSanPhamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DMQUYETTIEN.Models;
using System.Transactions;
namespace DMQUYETTIEN.Controllers
{
    public class BangSanPhamController : Controller
    {
        private CS4PEEntities db = new CS4PEEntities();

        // GET: /BangSanPham/
        public ActionResult Index()
        {
            var bangsanphams = db.BangSanPhams.Include(b => b.LoaiSanPham);
            return View(bangsanphams.ToList());
        }

        // GET: /BangSanPham/Details/5
        public FileResult Details(string id)
        {
            var path = Server.MapPath("~/App_Data/" + id);
            return File(path, "images");
        }


        // GET: /BangSanPham/Create4   
        public ActionResult Create()
        {
            ViewBag.Loai_id = new SelectList(db.LoaiSanPhams, "id", "TenLoai");
            return View();
        }

        // POST: /BangSanPham/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BangSanPham model)
        {
            CheckBangSanPham(model);
            if (ModelState.IsValid)
            {
                using ( var scope = new TransactionScope() ){
                    db.BangSanPhams.Add(model);
                    db.SaveChanges();

                    var path = Server.MapPath("~/App_Data");
                    path = path + "/" + model.id;
                    if (Request.Files["HinhAnh"] != null && Request.Files["HinhAnh"].ContentLength > 0){
                        Request.Files["HinhAnh"].SaveAs(path);
                        scope.Complete();                        
                        return RedirectToAction("Index");
                    }
                    else
                        ModelState.AddModelError("HinhAnh","Chưa có hình ảnh nào hít :p");
                    
                }                
            }

            ViewBag.Loai_id = new SelectList(db.LoaiSanPhams, "id", "TenLoai", model.Loai_id);
            return View(model);
        }
        private void CheckBangSanPham(BangSanPham model)
        {
            if (model.GiaGoc < 0)
                ModelState.AddModelError("GiaGoc", "Giá gốc phải > 0");
            if (model.GiaBan < model.GiaGoc)
                ModelState.AddModelError("GiaBan", "Giá gốc phải > Giá Bán");
            if (model.GiaGop < model.GiaGoc)
                ModelState.AddModelError("GiaGop", "Giá gốc phải > Giá Góp");  
            
        }

        // GET: /BangSanPham/Edit/5
        public ActionResult Edit(int id)
        {
            BangSanPham model = db.BangSanPhams.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            ViewBag.Loai_id = new SelectList(db.LoaiSanPhams, "id", "TenLoai", model.Loai_id);
            return View(model);
        }

        // POST: /BangSanPham/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BangSanPham model)
        {
            CheckBangSanPham(model);
            if (ModelState.IsValid)
            {
                using (var scope = new TransactionScope())
                {
                    db.Entry(model).State = EntityState.Modified;
                    db.SaveChanges();
                    var path = Server.MapPath("~/App_Data");
                    path = path + "/" + model.id;
                    if (Request.Files["HinhAnh"] != null &&
                        Request.Files["HinhAnh"].ContentLength > 0)
                    {
                        Request.Files["HinhAnh"].SaveAs(path);
                    }
                    scope.Complete(); // approve for transaction
                    return RedirectToAction("Index");
                }
            }
            ViewBag.Loai_id = new SelectList(db.LoaiSanPhams, "id", "TenLoai", model.Loai_id);
            return View(model);
        }

        // GET: /BangSanPham/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BangSanPham bangsanpham = db.BangSanPhams.Find(id);
            if (bangsanpham == null)
            {
                return HttpNotFound();
            }
            return View(bangsanpham);
        }

        // POST: /BangSanPham/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BangSanPham bangsanpham = db.BangSanPhams.Find(id);
            db.BangSanPhams.Remove(bangsanpham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DMQUYETTIEN/DMQUYETTIEN/Views/BangSanPham/Create.cshtml
@model DMQUYETTIEN.Models.BangSanPham

@{
    ViewBag.Title = "Tạo mới";
}

<h2>Tạo mới nè</h2>


@using (Html.BeginForm("Create", "BangSanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bảng Sản Phẩm</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.MaSP, "Mã sản phẩm", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.MaSP, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaSP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSP, "Tên sản phẩm", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.TenSP, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TenSP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Loai_id, "Loại sản phẩm", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Loai_id", (IEnumerable<SelectListItem>)ViewData["Loai_id"], new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Loai_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, "Giá bán", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaBan, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GiaBan)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaGoc, "Giá gốc", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaGoc, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GiaGoc)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaGop, "Giá góp", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaGop, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GiaGop)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongTon, "Số lượng tồn", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SoLuongTon, new { type = "number", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SoLuongTon)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("HinhAnh", "Hình Sản Phẩm", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("HinhAnh", null, new { type = "file", onchange = "readURL(this)", @class = "form-control" })
                @Html.ValidationMessage("HinhAnh")
                <img id="imgsp" src="" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Tạo điii" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay trở lại hui", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
   <script>
       function readURL(input) {
           if (input.files && input.files[0]) {
               var reader = new FileReader();

               reader.onload = function (e) {
                   $('#imgsp')
                       .attr('src', e.target.result)
                       .width(150)
                       .height(200);
               };

               reader.readAsDataURL(input.files[0]);
           }
       }
    </script>
}

DMQUYETTIEN/DMQUYETTIEN/Views/BangSanPham/Delete.cshtml
@model DMQUYETTIEN.Models.BangSanPham

@{
    ViewBag.Title = "Xóa";
}

<h2>Xóa nào</h2>

<h3>Bạn có chắc chứ, xóa là mất đó?</h3>
<div>
    <h4>bảng Sản Phẩm</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Mã Sản Phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaSP)
        </dd>

        <dt>
            Tên Sản Phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSP)
        </dd>

        <dt>
            Giá Bán
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaBan)
        </dd>

        <dt>
            Giá Gốc
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaGoc)
        </dd>

        <dt>
            Giá Góp
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaGop)
        </dd>

        <dt>
            Số Lượng Tồn Kho
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongTon)
        </dd>

        <dt>
            Loại Sản Phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSanPham.TenLoai)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa nè :<" class="btn btn-default" /> |
            @Html.ActionLink("Quay trở lại hui", "Index")
        </div>
    }
</div>

DMQUYETTIEN/DMQUYETTIEN/Views/BangSanPham/Details.cshtml
@model DMQUYETTIEN.Models.BangSanPham

@{
    ViewBag.Title = "Details";
}

<h2>Chi tiết nè</h2>

<div>
    <h4>Bảng Sản Phẩm</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            Mã Sản Phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaSP)
        </dd>

        <dt>
            Tên Sản Phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSP)
        </dd>

        <dt>
            Giá Bán
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaBan)
        </dd>

        <dt>
            Giá Gốc
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaGoc)
        </dd>

        <dt>
            Giá Góp
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaGop)
        </dd>

        <dt>
            Số Lượng Tồn Kho
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongTon)
        </dd>

        <dt>
            Loại Sản Phẩm
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSanPham.TenLoai)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Chỉnh sửa đi", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Quay trở lại hui", "Index")
</p>

DMQUYETTIEN/DMQUYETTIEN/Views/BangSanPham/Edit.cshtml
@model DMQUYETTIEN.Models.BangSanPham

@{
    ViewBag.Title = "Edit";
}

<h2>Chỉnh sửa nè</h2>


@using (Html.BeginForm("Edit", "BangSanPham", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bảng Sản Phẩm</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.MaSP,"Mã Sản Phẩm", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.MaSP, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaSP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenSP,"Tên Sản Phẩm" ,new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.TenSP, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TenSP)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Loai_id,"Loại id", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Loai_id, (IEnumerable<SelectListItem>)ViewData["Loai_id"], new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Loai_id)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan,"Giá Bán" ,new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaBan, new { @class = "form-control", type = "number" })
                @Html.ValidationMessageFor(model => model.GiaBan)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaGoc,"Giá Gốc" ,new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaGoc, new { @class = "form-control", type = "number" })
                @Html.ValidationMessageFor(model => model.GiaGoc)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiaGop,"Giá Góp" ,new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.GiaGop, new { @class = "form-control", type = "number" })
                @Html.ValidationMessageFor(model => model.GiaGop)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongTon,"Số Lượng Tồn", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.SoLuongTon, new { @class = "form-control", type = "number" })
                @Html.ValidationMessageFor(model => model.SoLuongTon)
            </div>
        </div>
        <div class="form-group">
            @Html.Label("HinhAnh", "Hình sản phẩm", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("HinhAnh", null, new { type = "file", onchange = "readURL(this);", @class = "form-control" })
                @Html.ValidationMessage("HinhAnh")
                <img id="HinhSP" src="@Url.Action("Details", new { id = Model.id })" width="150" height="100" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu nè" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay trở lại hui", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#HinhSP').attr('src', e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
}

DMQUYETTIEN/DMQUYETTIEN/Views/BangSanPham/Index.cshtml
@model IEnumerable<DMQUYETTIEN.Models.BangSanPham>

@{
    ViewBag.Title = "Trang chủ";
}

<h2>Bảng Sản Phẩm</h2>

<p>
    @Html.ActionLink("Tạo mới", "Create")
</p>
<table id="BangSanPham" class="table table-bordered table-condensed table-hover table-responsive table-striped">
    <thead>
        <tr class="table danger">
            <th>
                Mã sản phẩm
            </th>
            <th>
                Tên Sản Phẩm
            </th>
            <th>
                Giá Bán
            </th>
            <th>
                Giá Gốc
            </th>
            <th>
                Giá Góp
            </th>
            <th>
                Số Lượng Tồn Kho
            </th>
            <th>
                Tên Loại
            </th>    
            <th>Hình Sản Phẩm</th>        
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.MaSP
                </td>
                <td>
                    @item.TenSP
                </td>
                <td>
                    @item.GiaBan.ToString("N0")
                </td>
                <td>
                    @item.GiaGoc.ToString("N0")
                </td>
                <td>
                    @item.GiaGop.ToString("N0")
                </td>
                <td>
                    @item.SoLuongTon.ToString("N0")
                </td>
                <td><img src="@Url.Action("Details", new { id = item.id })" width="150" height="100" /></td>
                <td>
                    @item.LoaiSanPham.TenLoai
                </td>
                <td>
                    <a title="Sửa" href="@Url.Action("Edit",new { id = item.id })">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                    <a title="Xem chi tiết" href="@Url.Action("Details",new { id = item.id }) ">
                        <span class="glyphicon glyphicon-list-alt"></span>
                    </a>
                    <a title="Xóa" href="@Url.Action("Delete",new { id = item.id }) ">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>                    
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts {
    <link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>    
    <script>
        $(document).ready(function () {
            $('#BangSanPham').DataTable();
        });
    </script>
}